x86_64-xen-pv: Fix compilation problem
Remove property "stack-probes" as it generates the following
compilation error:

$ rustc --version
rustc 1.57.0-nightly (5ecc8ad84 2021-09-19)
$
$ cargo build --target x86_64-xen-pv.json
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target /home/mpoirier/work/stratos/xen/xen-sys/x86_64-xen-pv.json --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: `Boolean(false)` is not a valid value for `stack-probes`: expected a JSON object. Run `rustc --print target-list` for a list of built-in targets

This issue has also been reported for another crate here[1].

[1]. https://github.com/o8vm/rust_dos/pull/5

Signed-off-by: Mathieu Poirier <mathieu.poirier@linaro.org>